name: Deploy to EC2

on:
  workflow_run:
    workflows:
      - "Build and Push to Dockerhub"
    types:
      - completed

env:
  IMAGE_NAME: v-controller

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

            # Stop and remove the old container if it exists
            docker stop controller || true
            docker rm controller || true

            # Run the new container with environment variables
            docker run -d \
              --name controller \
              -p 3001:3001 \
              -e PORT=3001 \
              -e REDIS_HOST=redis-12944.c61.us-east-1-3.ec2.redns.redis-cloud.com \
              -e REDIS_PORT=12944 \
              -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -e AWS_REGION=${{ secrets.AWS_REGION }} \
              -e AWS_INPUT_BUCKET=${{ secrets.AWS_INPUT_BUCKET }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
              -e REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} \
              charu167/v-controller:latest